// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWRe3kPvuP9m6SYS1CnpjCAwSb2AVXnmw',
    appId: '1:459213220642:web:3aba3f94f32d402dff937b',
    messagingSenderId: '459213220642',
    projectId: 'fasum-bb362',
    authDomain: 'fasum-bb362.firebaseapp.com',
    databaseURL: 'https://fasum-bb362-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fasum-bb362.firebasestorage.app',
    measurementId: 'G-C818ETV35P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwuXjRWjbNnDj7szAOBs_Rd5d3dYMEOWI',
    appId: '1:459213220642:android:951a3a2abc5aa0abff937b',
    messagingSenderId: '459213220642',
    projectId: 'fasum-bb362',
    databaseURL: 'https://fasum-bb362-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fasum-bb362.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtXuzolQov_Y8XlztGwgqtI4JQtQTsb2w',
    appId: '1:459213220642:ios:24ebfa0ed659a0beff937b',
    messagingSenderId: '459213220642',
    projectId: 'fasum-bb362',
    databaseURL: 'https://fasum-bb362-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fasum-bb362.firebasestorage.app',
    iosClientId: '459213220642-gm81ksffek3cljdur6f1jbl7m3ugjmpb.apps.googleusercontent.com',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtXuzolQov_Y8XlztGwgqtI4JQtQTsb2w',
    appId: '1:459213220642:ios:24ebfa0ed659a0beff937b',
    messagingSenderId: '459213220642',
    projectId: 'fasum-bb362',
    databaseURL: 'https://fasum-bb362-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fasum-bb362.firebasestorage.app',
    iosClientId: '459213220642-gm81ksffek3cljdur6f1jbl7m3ugjmpb.apps.googleusercontent.com',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWRe3kPvuP9m6SYS1CnpjCAwSb2AVXnmw',
    appId: '1:459213220642:web:fa17c7e174dccb05ff937b',
    messagingSenderId: '459213220642',
    projectId: 'fasum-bb362',
    authDomain: 'fasum-bb362.firebaseapp.com',
    databaseURL: 'https://fasum-bb362-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fasum-bb362.firebasestorage.app',
    measurementId: 'G-453PMPWQWT',
  );
}
