// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiWLTdFeX-obIxEp209GmBPyBqnQA4BZI',
    appId: '1:930533960461:web:2ff09c72b1d5263e171e44',
    messagingSenderId: '930533960461',
    projectId: 'first-app-2bf97',
    authDomain: 'first-app-2bf97.firebaseapp.com',
    databaseURL: 'https://first-app-2bf97-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-2bf97.firebasestorage.app',
    measurementId: 'G-7TN4NTC0SQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9IY6JhXp0hTeSXXY_XEAnk76suS2Dk7s',
    appId: '1:930533960461:android:eee023e405f0d8a0171e44',
    messagingSenderId: '930533960461',
    projectId: 'first-app-2bf97',
    databaseURL: 'https://first-app-2bf97-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-2bf97.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX1688CLWP2-AkAzRsLPkJg4VL63bBHXE',
    appId: '1:930533960461:ios:7b5fa72c8baa08f0171e44',
    messagingSenderId: '930533960461',
    projectId: 'first-app-2bf97',
    databaseURL: 'https://first-app-2bf97-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-2bf97.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX1688CLWP2-AkAzRsLPkJg4VL63bBHXE',
    appId: '1:930533960461:ios:7b5fa72c8baa08f0171e44',
    messagingSenderId: '930533960461',
    projectId: 'first-app-2bf97',
    databaseURL: 'https://first-app-2bf97-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-2bf97.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiWLTdFeX-obIxEp209GmBPyBqnQA4BZI',
    appId: '1:930533960461:web:bc7b371bb39e3ef1171e44',
    messagingSenderId: '930533960461',
    projectId: 'first-app-2bf97',
    authDomain: 'first-app-2bf97.firebaseapp.com',
    databaseURL: 'https://first-app-2bf97-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-2bf97.firebasestorage.app',
    measurementId: 'G-9JFJPYB3H3',
  );

}